### ISSUE TITLE
what's 'SWA' callback?

### ISSUE THREAD

**Issue by saxh** [boat-group/fancy-nlp#1]
what's 'SWA' callback?

**Comment by AlexYangLi** [comment]
Hi! 'SWA' is a weight ensemble strategy.   
  
During a single training process, we maintain a copy of model's weights ![](http://latex.codecogs.com/gif.latex?w_{a}) in memory, which is used to keep track of the averaged weights. After each epoch of training, we update the weights of the copy :  
![](http://latex.codecogs.com/gif.latex?w_{a}=\\frac{w_{a}*n_{models}+w}{n_{models}+1})    
where ![](http://latex.codecogs.com/gif.latex?n_{models}) is the number of models already included in the average and ![](http://latex.codecogs.com/gif.latex?w) represents the weights of the model being trained. This amounts to storing the running average of the models seen at the end of each epoch of training.  

For further details, I refer you to this paper: [Averaging Weights Leads to Wider Optima and Better Generalization](https://arxiv.org/abs/1803.05407)
