### ISSUE TITLE
这个能自己训练吗

### ISSUE THREAD

**Issue by xxllp** [boat-group/fancy-nlp#3]

**Comment by AlexYangLi** [comment]
你好，可以自己训练的。以命名实体识别任务为例，加载NER实例之后，准备好训练数据，然后调用fit函数，并在其中指定使用的ner模型类型，这样便可以开始训练了。下图是训练一个基于bert的NER模型的例子：

![image](https://user-images.githubusercontent.com/30424821/69837180-85ed6000-1288-11ea-9aa3-5d6de97f8c83.png)

**Comment by xxllp** [comment]
看了下文档感觉很不错  requirements 里面有些库 版本太低了 跟本地冲突了 比如tf

**Comment by eshijia** [comment]
> 看了下文档感觉很不错 requirements 里面有些库 版本太低了 跟本地冲突了 比如tf

这里受限于与公司其它系统的兼容，主要是protobuf的版本必须使用3.4.0，所以我们对tf的版本进行了限制，后续我们会开放适配更高版本的tf的pipeline。

**Comment by eshijia** [comment]
@xxllp 目前，我们已经发布了最新的1.0.0版本，全面基于tf 2.1 构建。

**Comment by yuzhanggdut** [comment]
有验证过ner任务的效果吗？

**Comment by eshijia** [comment]
> 有验证过ner任务的效果吗？

你可以自行加载训练过的模型，用于任务部署。近期我们会发布多种当前流行模型的对比评测，欢迎关注。
